name: CI
on:
  push:
    branches:
      - 'dev/**'
  pull_request:
    branches: 
      - 'dev/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4z

      - name: Run Docker Compose File
        run:
zzz
        env:
          DOCKERFILE: Dockerfile.dev


        
