name: CI
on:
  push:
    branches:
      - 'dev/**'
      - 'dev'
  pull_request:
    branches: 
      - 'dev/**'
      - 'dev'

  workflow_dispatch:
#zz
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: docker compose -f compose.yml up --build
        env:
          DOCKERFILE: Dockerfile.dev

      - name: Shut down
        run: docker compose down

        
